### ISSUE TITLE
Add weather summary to either chart or data points

### ISSUE THREAD

**Issue by andybyte** [erl67/IS1017project#24]
This is something I forgot to do. I have the array already I just need to add it in.

**Comment by njscholfield** [comment]
I think it would be better to add it to the data points (when you click/hover) I don't want the graph to get too crowded. Up to you though

**Comment by andybyte** [comment]
I agree. The approach I took didn't work so I'll give one more try. But yeah, I don't want to crowd the chart with the words so I'll just try to add it to the click/hover point.
